version: 2
jobs:
  build:
    docker:
    - image: circleci/FROM golang:1.21-bullseye
    steps:
    - checkout
    - restore_cache:
        keys:
          - go-build-cache
    - run: go test -v ./...
    - save_cache:
        key: go-build-cache
        paths:
          - ~/.cache/go-build
